### ISSUE TITLE
Play in External Player Option Bugged on PC specifically

### ISSUE THREAD

**Issue by ChaoDrake** [Stremio/stremio-web#544] opened 2023-12-22 16:51 UTC
With the new update, for some reason the play in external player option on my PC is no longer working. I have tried multiple different browsers (Brave, Chrome, Firefox, Edge) and none of them seem to work. I have also tried clearing cookies and still nothing. What I did try was opening Stremio Web on my mobile browser and it seems to work perfectly fine there. What could be causing this issue?

See images below for clarification. Image 1 is before recent update and Image 2 is with current update.

![Screenshot 2023-12-20 203846](https://github.com/Stremio/stremio-web/assets/43890693/2fcbe05b-35ce-423e-96f1-93255381cd9e)
![Screenshot 2023-12-20 203947](https://github.com/Stremio/stremio-web/assets/43890693/d1f3e980-3aa0-49db-9d51-e657d7cdce6c)

**Comment by Iheuzio** [comment] 2023-12-27 18:11
Can you please share the steps and what is expected? Some external players are not supported.

**Comment by ChaoDrake** [comment] 2023-12-27 18:23
The steps are opening Stremio Web on web.stremio.com and navigating to settings, and then to the play in external player option and there, it used to have VLC player as an option, but it is currently bugged and only says disabled. Seems to work on mobile browser but not browser on PC.

As you see in the above attached pictures, I was using VLC and it recognized just fine before the recent update.

**Comment by ChaoDrake** [comment] 2023-12-27 18:31
Also, someone has reported this on reddit and the person who seems to be related with stremio development or support has confirmed this bug and reported it to the devs.

https://www.reddit.com/r/Stremio/comments/18oov8r/play_in_external_player_setting_is_broken_in_the/

**Comment by kKaskak** [comment] 2023-12-30 11:17
> Also, someone has reported this on reddit and the person who seems to be related with stremio development or support has confirmed this bug and reported it to the devs.
> 
> https://www.reddit.com/r/Stremio/comments/18oov8r/play_in_external_player_setting_is_broken_in_the/

There were some changes made in the recent update of `stremio-web` specifically related to the external player feature. You can look them up here --> https://github.com/Stremio/stremio-web/commit/f5a0bc86e5bcd06e5e96f64582a0baf860edb656#diff-8fd62db88a301de4883a1f515697a13b95b50e6a9f368349b3b6f76e004e7fe3R43 
There are now new players added, and you can check yourself which players are supported on different operating systems.

**Comment by ChaoDrake** [comment] 2023-12-30 17:22
Thank you, if I'm reading the code correctly, it seems that the platform "windows" only shows up for label "EXTERNAL_PLAYER_DISABLED", value: null. Under the label/value for VLC it only has the platforms "ios" and "android"

Is there a reason why "windows" is no longer a platform under any other external players? For sure at least VLC should be supported as it was supported before this recent change.

**Comment by kKaskak** [comment] 2023-12-30 18:37
> Thank you, if I'm reading the code correctly, it seems that the platform "windows" only shows up for label "EXTERNAL_PLAYER_DISABLED", value: null. Under the label/value for VLC it only has the platforms "ios" and "android"
> 
> Is there a reason why "windows" is no longer a platform under any other external players? For sure at least VLC should be supported as it was supported before this recent change.

I will look into this and give you an answer tomorrow.

**Comment by kKaskak** [comment] 2024-01-02 08:15
> Thank you, if I'm reading the code correctly, it seems that the platform "windows" only shows up for label "EXTERNAL_PLAYER_DISABLED", value: null. Under the label/value for VLC it only has the platforms "ios" and "android"
> 
> Is there a reason why "windows" is no longer a platform under any other external players? For sure at least VLC should be supported as it was supported before this recent change.

Hi. We discussed this with the team. This option still works. When the stream fails to play, you have the possibility to download the playlist and play in a player of your choice.

**Comment by ChaoDrake** [comment] 2024-01-02 15:26
I'm sorry, I'm not sure I understand. Previously there was an option to automatically choose VLC as your external player and when you played a stream it automatically opens in VLC. Currently, there is no option for automatically opening in VLC and only says "Disabled". I'm not quite understanding how this is a feature not a bug, if anything it's the removal of a previous feature. The provided solution you gave seems more of a workaround if anything.

Also I'm not understanding why the option to play in external player works on a mobile browser but not on a browser on Windows, and to reiterate, this worked before the recent update. See above images.

**Comment by prom3theu5** [comment] 2024-01-02 20:05
> > Thank you, if I'm reading the code correctly, it seems that the platform "windows" only shows up for label "EXTERNAL_PLAYER_DISABLED", value: null. Under the label/value for VLC it only has the platforms "ios" and "android"
> > Is there a reason why "windows" is no longer a platform under any other external players? For sure at least VLC should be supported as it was supported before this recent change.
> 
> Hi. We discussed this with the team. This option still works. When the stream fails to play, you have the possibility to download the playlist and play in a player of your choice. Will close this soon if it works for you. Basically, this is a feature not a bug.

Sorry but I don't think this is a feature lol. More like a regression.
I too will report the issue with beta 4
Basically (not tested other browsers) in edge clear application cache, and reload `web.stremio.com` and go to settings
You will find that there are no external players you can choose, the external players box only has the default value of "Disabled" in the input box, like so

![image](https://github.com/Stremio/stremio-web/assets/1518610/c641ca93-72aa-4fd2-8544-0ee9686d4713)
 
and in settings you can see `playerType` is `null`

![image](https://github.com/Stremio/stremio-web/assets/1518610/b08a56d8-5d88-4fe2-a0b7-692e2594517b)

If you manually change the profile json in local storage to "playerType": "vlc", vlc will be shown as selected in the external player box, and vlc will work - but the moment you open the dropdown box again it will be lost.

**Comment by kKaskak** [comment] 2024-01-02 21:05
> > > Thank you, if I'm reading the code correctly, it seems that the platform "windows" only shows up for label "EXTERNAL_PLAYER_DISABLED", value: null. Under the label/value for VLC it only has the platforms "ios" and "android"
> > > Is there a reason why "windows" is no longer a platform under any other external players? For sure at least VLC should be supported as it was supported before this recent change.
> > 
> > 
> > Hi. We discussed this with the team. This option still works. When the stream fails to play, you have the possibility to download the playlist and play in a player of your choice. Will close this soon if it works for you. Basically, this is a feature not a bug.
> 
> Sorry but I don't think this is a feature lol. More like a regression. I too will report the issue with beta 4 Basically (not tested other browsers) in edge clear application cache, and reload `web.stremio.com` and go to settings You will find that there are no external players you can choose, the external players box only has the default value of "Disabled" in the input box, like so
> 
> ![image](https://private-user-images.githubusercontent.com/1518610/293778600-c641ca93-72aa-4fd2-8544-0ee9686d4713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjk3NjIsIm5iZiI6MTcwNDIyOTQ2MiwicGF0aCI6Ii8xNTE4NjEwLzI5Mzc3ODYwMC1jNjQxY2E5My03MmFhLTRmZDItODU0NC0wZWU5Njg2ZDQ3MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMjEwNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZmZTc3N2Q4ZGJhNWM2N2JhNDA0ZjUxOTlhMjExM2JmODhkNzYzN2ZhOWU0NjRjN2U3NDRmYjU1ZWMyNWYzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aO7LaHVqOk4Gi1MdpdfeM4W8bhKh_0elASd4aRP3z1o)
> 
> and in settings you can see `playerType` is `null`
> 
> ![image](https://private-user-images.githubusercontent.com/1518610/293778897-b08a56d8-5d88-4fe2-a0b7-692e2594517b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjk3NjIsIm5iZiI6MTcwNDIyOTQ2MiwicGF0aCI6Ii8xNTE4NjEwLzI5Mzc3ODg5Ny1iMDhhNTZkOC01ZDg4LTRmZTItYTBiNy02OTJlMjU5NDUxN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMjEwNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMGY3YjQ3MzlmNDIzYmQ0MjM1ZDZkZmZiOTE5N2U4MzkwM2ZiNjBlNjU3YTdjMDFiYmZiZTYyMjIxOGY4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zyu0WN2-bLGlFP6YHUV-3rzmR8k9myX_1IaDMF-9rlY)
> 
> If you manually change the profile json in local storage to "playerType": "vlc", vlc will be shown as selected in the external player box, and vlc will work - but the moment you open the dropdown box again it will be lost.

Yes, I'm aware of the fact that it works. Will discus this with the team again.

**Comment by kKaskak** [comment] 2024-01-08 15:41
@prom3theu5 @ChaoDrake @Iheuzio The team has decided that this will be fixed in the next app update. Thanks for your patience.

**Comment by ChaoDrake** [comment] 2024-01-08 17:38
Thank you for your help @kKaskak , much appreciated!

**Comment by cransono** [comment] 2024-02-28 20:04
It is February 28th. It does not appear as fixed yet. Just wanted to check on an ETA for the fix.

**Comment by elpiel** [comment] 2024-03-01 14:33
Hello,
There was a PR to fix this issue, it's is not a regression as e.g. VLC was not actually supported by `stremio-core` for Linux/Windows, only Android and iOS, even though the settings allowed you to set VLC as external player.

Please use this reference to the PR that made the change and the discussion between @tymmesyde and me:

https://github.com/Stremio/stremio-web/pull/542/files#r1432439664

Edit: Another note, there are 2 different places that list "External player"
1. Is the Settings - External player to always play a stream in external player
2. In the web Player itself you have settings `...` (3 dots) and there you have the option to open the given stream in an External Player, VLC should be showing there.

**Comment by ChaoDrake** [comment] 2024-03-01 19:07
So you're saying that it's not a regression as it was never supported by stremio-core, but as shown by the images in the first post, it did before the most recent update. And I am referencing the one that's in Settings - External player to always play a stream in external player.

While it is still true that in the web player itself, you can still select the setting to open VLC, it is an extra step whereas before where it would open automatically.

Currently, I use a workaround and run the stremio-web page as a mobile device so I can choose VLC as an external player and then set the .m3u files to always open with VLC and it kinda works that way. It's a little clunky but it does what I want where I just wanna press play and it opens VLC.

**Comment by elpiel** [comment] 2024-03-03 15:28
As far as I understood my colleague @tymmesyde , VLC does not support a URI Scheme on desktop, only Android and iOS.

References:
- Script for redirecting vlc:// URI to vlc - https://www.autohotkey.com/boards/viewtopic.php?f=6&t=62537
- VLC for Android vlc:// URI scheme issue- https://code.videolan.org/videolan/vlc-android/-/issues/527
- And last but not least, I found this forum comment talking about `vlc-x-callback` but again for **iOS** - https://forum.videolan.org/viewtopic.php?t=120695#p418032

**Comment by ChaoDrake** [comment] 2024-03-04 14:16
So I guess my question is, why did it work before? Did an update with VLC break this feature? Or were you using a different way to open VLC by default?

**Comment by Tranquilito** [comment] 2024-03-13 15:27
Any update on this one ? March 2024 still having the issue.

**Comment by iPromKnight** [comment] 2024-03-13 15:32
@elpiel 
It's not so much that vlc isn't supported. It's that the external players box doesn't expand so you can't select Allow Choosing like you can in the other platforms which simply outputs an m3u file that will open in any external app you have
This, along with the fact that synopsis is broken, is the reason I just host my own instance based on beta.0 which is miles better than beta 1 2 3 or 4
It's been regression after regression ever since for anyone using non mobile devices from the web.

**Comment by kKaskak** [comment] 2024-03-28 18:12
https://github.com/Stremio/stremio-web/pull/599

**Closed as completed by kKaskak** 2024-03-28 18:12 UTC

**Comment by MMALI3287** [comment] 2024-09-19 17:33
Is there any support for choosing any installed external player from Stremio to play?

**Comment by spidy2356** [comment] 2026-04-05 07:53
for me, on web version and desktop version only m3u playlist option shown
and download stream as m3u

**Comment by ChaoDrake** [comment] 2026-04-05 19:30
yeah, it's been that way for two years now. It doesn't look like they're looking to change that. I just let it download as m3u and open m3u automatically with my preferred external player.
