### ISSUE TITLE
Mouse does not hide while streaming on MacOS

### ISSUE THREAD

**Issue by plimao** [Stremio/stremio-web#505] opened 2023-11-07 19:01 UTC
Mouse hides on VLC and any other player i try using MacOS except Stremio's player.
Issue is replicated on Stremio player both in MacOS Ventura 13.6 and also the most recent Somona.

**Comment by elpiel** [comment] 2023-11-08 08:57
Hello, I'm moving this issue as it's related to stremio-web and it's player.

**Comment by elpiel** [comment] 2023-11-08 09:08
Duplicate of Stremio/stremio-bugs#1081

**Comment by kKaskak** [comment] 2023-12-30 11:11
The mouse correctly hides on the `stremio-web` player. Sonoma 14.1.1.

**Comment by kKaskak** [comment] 2023-12-30 11:12
> Mouse hides on VLC and any other player i try using MacOS except Stremio's player. Issue is replicated on Stremio player both in MacOS Ventura 13.6 and also the most recent Somona.

Can you specify where it does not hide? Is it the desktop app or the web app?

**Comment by pedrocarvalhlima** [comment] 2023-12-30 13:15
the bug happens in many different odd occasions but it's not hard to replicate on a mbp 14. the mouse never hides if I put it on the left or right margins, I have to move it again to the center of the screen and then it hides. I think it has something to do with being outside the expected area where the mouse would be, or because it's outside the stremio window.

**Comment by pedrocarvalhlima** [comment] 2023-12-30 13:18
Keep in mind I say outside the stremio window but this behaviour happens when the app is full screen. I'm just assuming there's some odd margin thing happening with how stremio does Fullscreen that doesn't happen for example when I Fullscreen youtube on chrome.

**Comment by kKaskak** [comment] 2023-12-30 16:13
> Keep in mind I say outside the stremio window but this behaviour happens when the app is full screen. I'm just assuming there's some odd margin thing happening with how stremio does Fullscreen that doesn't happen for example when I Fullscreen youtube on chrome. 

Can you provide a screen recording of the issue? Thanks 🙏🏻 I tried it on my mpa M2 and couldn't replicate the issue.

**Comment by kKaskak** [comment] 2024-03-28 13:05
Any updates on that? @pseudolimonada I asked you if this is about the desktop app or the web app?

**Comment by kKaskak** [comment] 2024-04-09 11:09
Closing due to inactivity

**Closed as completed by kKaskak** 2024-04-09 11:09 UTC
Labels: low-hanging-fruit
